# -*- coding: utf-8 -*-
"""simple_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Subhajit62/c635dfe73ae0bf5c29cd3bb3d445434b/simple_calculator.ipynb

# Calculator
1. Addition
2. Substraction
3. Multiplication
4. Integer Division
5. Float division
6. Mod
7. percentage
8. Factorial
"""

def add(num1, num2):
    return num1 + num2

def substraction(num1, num2):
    return abs(num1-num2)

def multiplication(num1, num2):
    return num1*num2

def integer_division(num1, num2):
    return num1//num2

def float_division(num1 , num2):
    return num1/num2

def mod(num1 , num2):
    return num1%num2

def percentage(num1, num2):
    return (num1/num2) * 100

def power(num1,num2):
    return num1**num2

def factorial(num):
    if num==0:
        return 1
    return num * factorial(num-1)

def calculator():
    user_input = int(input("Please enter the number associated with your operation -\n" \
                     "1. Addition -\n" \
                     "2. Substraction -\n" \
                     "3. Multiplication -\n" \
                     "4. Integer Division -\n" \
                     "5. Float Division -\n" \
                     "6. Modulus -\n" \
                     "7. Percentage -\n" \
                     "8. power -\n" \
                     "9. Factorial -\n" \
                           " "))

    if user_input == 1:
      num1,num2 = input("Enter 2 numbers ").split()
      num1,num2 = int(num1),int(num2)
      print("Solution is", add(num1,num2))
    elif user_input == 2:
      num1,num2 = input("Enter 2 numbers ").split()
      num1,num2 = int(num1),int(num2)
      print("Solution is", substraction(num1,num2))
    elif user_input == 3:
      num1,num2 = input("Enter 2 numbers ").split()
      num1,num2 = int(num1),int(num2)
      print("Solution is", multiplication(num1,num2))
    elif user_input == 4:
      num1,num2 = input("Enter 2 numbers - dividend and divisor respectively ").split()
      num1,num2 = int(num1),int(num2)
      if num2 == 0:
        print("Error! Division by zero is not possible Enter valid values.")
        calculator()
      print("Solution is", integer_division(num1,num2))
    elif user_input == 5:
      num1,num2 = input("Enter 2 numbers - dividend and divisor respectively ").split()
      num1,num2 = int(num1),int(num2)
      if num2 == 0:
        print("Error! Division by zero is not possible Enter valid values.")
        calculator()
      print("Solution is", float_division(num1,num2))
    elif user_input == 6:
      num1,num2 = input("Enter 2 numbers - dividend and divisor respectively ").split()
      num1,num2 = int(num1),int(num2)
      if num2 == 0:
        print("Error! Division by zero is not possible Enter valid values.")
        calculator()
      print("Solution is", mod(num1,num2))
    elif user_input == 7:
      num1,num2 = input("Enter the number whose percentage you want to get followed by the bigger number ").split()
      num1,num2 = int(num1),int(num2)
      if num2 == 0:
        print("Error! Division by zero is not possible Enter valid values.")
        calculator()
      print("Solution is", percentage(num1,num2))
    elif user_input == 8:
      num1,num2 = input("Enter 2 numbers - Base and power respectively ").split()
      num1,num2 = int(num1),int(num2)
      print("Solution is", power(num1,num2))
    elif user_input == 9:
      num1 = int(input("Enter the number "))
      print("Solution is", factorial(num1))
    else:
      print("Please enter a valid input")
      calculator()